name: Model CI
on: [push]

jobs:
  build-model:
    name: Build, test, and upload model
    runs-on: self-hosted
    steps:
#     - uses: actions/checkout@v1
#     - name: Set up Python 3.7
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.7
     
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
        
    - name: Train model
      run: |
        rasa train
        
    - name: Run Through Test Stories
      run: |
        rasa test --stories test_stories/stories.md --fail-on-prediction-errors
    - name: Cross-validate NLU model
      run: |
        rasa test nlu --cross-validation
        
    - name: post cross-val results to PR
      uses: ShyamSunderRaja1/DIL_DigitalHuman@main
    
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: results.md
    
    - name: Upload model
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@master
      with:
        name: model
        path: models
        
